### ISSUE TITLE
Supplies for in-person

### ISSUE THREAD

**Issue by marty-downs** [lter/ssecr#28]
- [x] Tent cards with names (Jessica)
- [x] Large index cards or 8.5/11 cardstock for drawn profiles (CK?)
- [x] Markers (CK & MD)
- [x] Whiteboards (MD) - do we also need flip charts?
- [x] Whiteboard markers (MD)
- [x] Legos and printouts for lego activity (Nick, borrow from CoreR?)/Carrie - bring Monday am)

**Comment by njlyon0** [comment]
## Done!

We are in the in-person week now but we have all the stuff identified in the top-level comment so I think we're good to go ahead and close this (can always reopen as/if needed!)
