### ISSUE TITLE
Double Check Links on Fellows Page of SSECR Website

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#30]
## Summary

Making a demo issue to teach this concept / receive needed feedback.

## Sub-Tasks

- [x] Ping students to comment on issue
- [x] Make their edits

## Resources

- Relevant bit of SSECR website [here](https://lter.github.io/ssecr/fellows.html)

**Comment by hultingk** [comment]
LGTM

**Comment by lmnevins** [comment]
LGTM

**Comment by aeborgmeier** [comment]
LGTM

**Comment by bethany-williams** [comment]
Can you add my website link?
https://blw9786.wixsite.com/bethany-williams--ph

**Comment by rbrokaw** [comment]
LGTM

**Comment by jeremyacollings** [comment]
LGTM

**Comment by abulseco** [comment]
LGTM

**Comment by carlalopezll** [comment]
Would like to have my OrcID linked as well! And my name as Carla López Lloreda, without the hyphen :)

**Comment by moricandia** [comment]
LGTM

**Comment by kjsolomon** [comment]
Can you add my ORCID ID link? 
https://orcid.org/0000-0002-3646-4291

**Comment by naltmank** [comment]
github link for Noam goes to 404 not found! Should link to https://github.com/naltmank

Also orcid link: https://orcid.org/0000-0001-5175-3334

**Comment by juliannajollyrenzi** [comment]
Can you add link to my OrcID as well? https://orcid.org/0000-0002-6187-8656 :)

Also if the text could dance and turn into a sketch of my face that would be gr8!

**Comment by twalker1999** [comment]
Ditto: LGTM

**Comment by sbperez** [comment]
LGTM

**Comment by Smritipehimlimbu** [comment]
LGTM

**Comment by allie-case** [comment]
LGTM

**Comment by Francis-Chaves** [comment]
LGTM

**Comment by ppanwar11** [comment]
I am not on the web page.

**Comment by joeykriegerlodge** [comment]
Spelled my name wrong - KrIEger, not KrEIger

**Comment by Ian-Yiyang** [comment]
LGTM

**Comment by njlyon0** [comment]
This issue is related to improvements / learning objectives of the version control module (see #27 )

**Comment by njlyon0** [comment]
## Done!

All edits made and things are likely good on this front (will revisit as/if needed though)
