### ISSUE TITLE
Bug Fix: Team Science Practices

### ISSUE THREAD

**Issue by ckappel** [lter/ssecr#33]
## Summary

Broken link here: Lahr, Heather [How to effectively engage teams in interdisciplinary collaborations](https://lter.github.io/ssecr/How%20to%20effectively%20engage%20teams%20in%20interdisciplinary%20collaborations). 2024

## Sub-Tasks

- [x] Fix link

## Resources

- Bulleted list of broadly useful external links

**Comment by njlyon0** [comment]
## Done!

See [this commit](https://github.com/lter/ssecr/commit/2574c8ff04849c32564de494acf3d9525ed76f26#diff-530f88ae178d6a1dd0908d8c287943c0d16fa7107420767043ce19ee3e7378c0R65)
