### ISSUE TITLE
Image Captions?

### ISSUE THREAD

**Issue by marty-downs** [lter/ssecr#44]
## Summary

Cannot work out how to include both an alt-text and an image caption using the img src syntax that Nick prefers. What am I missing?

Image syntax copied from other examples on website goes like:
<img src="images/mind-map.png" alt="Bubble with a central concept or question, surrounded, at the first level, by inputs, outputs or modifiers and at the second level by question, concerns, or implications"  width="90%">

Seems like I should be able to add a caption (helpful for those NOT using screen readers) with the following syntax:

<img src="images/mind-map.png" fig-cap="Mind Map Example" alt="Bubble with a central concept or question, surrounded, at the first level, by inputs, outputs or modifiers and at the second level by question, concerns, or implications"  width="90%">

I've tried using caption, title, Title, fig-cap all to no avail. moving on the the rest of the content now. If someone knows the right syntax, I'd appreciate an assist.

**Comment by njlyon0** [comment]
Hey Marty!

Did you post this before we met and discussed it or is this a separate problem?

For posterity / just to check: 

the 'inclusive facilitation' module includes an image that has alt text and a figure caption. See the **image on the website [here](https://lter.github.io/ssecr/mod_facilitation.html#designing-meetings-for-all-thinking-styles)** and the **source code [here](https://github.com/lter/ssecr/blob/main/mod_facilitation.qmd#L230)**

Generally the syntax I use for this is as follows:

```
<p align="center">
<img src="image.png" alt=”DETAILED ALT TEXT HERE" width="80%"/>
<figcaption>FIGURE CAPTION TEXT HERE</figcaption>
</p>

```
